version: "3"
services:

  boatsandjoy-api:
    build:
      context: ../..
      dockerfile: environments/dev/Dockerfile
    env_file: ../../.env
    volumes:
      - "../../:/code"
    depends_on:
      - db
    ports:
      - "80:80"
    environment:
      - PYTHONIOENCODING=UTF-8
      - PYTHONUNBUFFERED=1
    command: python /code/manage.py runserver 0.0.0.0:80

  db:
    image: postgres:12
    restart: always
    env_file: ../../.env
    volumes:
      - ~/Dropbox/projects/boatsandjoy:/data
      - boatsandjoy-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025" # SMTP server
      - "8025:8025" # Web UI

  ngrok:
    image: wernight/ngrok
    links:
      - boatsandjoy-api
    command: ngrok http boatsandjoy-api:80
    ports:
      - "4040:4040" # Access to public domain: /api/tunnels

volumes:
  boatsandjoy-data: {}
